### ISSUE TITLE
Fails on android

### ISSUE THREAD

**Issue by pacifio** [sslcommerz/SSLCommerz-Flutter#4]
```
E/AndroidRuntime(29927): 	at com.sslwireless.sslcommerzlibrary.view.fragment.SSLCMobileBankingFragment.setMenuVisibility(SSLCMobileBankingFragment.java:399)
E/AndroidRuntime(29927): 	at androidx.fragment.app.FragmentPagerAdapter.setPrimaryItem(FragmentPagerAdapter.java:218)
E/AndroidRuntime(29927): 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1234)
E/AndroidRuntime(29927): 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
E/AndroidRuntime(29927): 	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
E/AndroidRuntime(29927): 	at android.view.View.measure(View.java:27131)
E/AndroidRuntime(29927): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
E/AndroidRuntime(29927): 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
E/AndroidRuntime(29927): 	at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:99)
E/AndroidRuntime(29927): 	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:2003)
E/AndroidRuntime(29927): 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:831)
E/AndroidRuntime(29927): 	at android.view.View.measure(View.java:27131)
E/AndroidRuntime(29927): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
E/AndroidRuntime(29927): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/AndroidRuntime(29927): 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
E/AndroidRuntime(29927): 	at android.view.View.measure(View.java:27131)
E/AndroidRuntime(29927): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
E/AndroidRuntime(29927): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
E/AndroidRuntime(29927): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
E/AndroidRuntime(29927): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
E/AndroidRuntime(29927): 	at android.view.View.measure(View.java:27131)
E/AndroidRuntime(29927): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
E/AndroidRuntime(29927): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/AndroidRuntime(29927): 	at android.view.View.measure(View.java:27131)
E/AndroidRuntime(29927): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
E/AndroidRuntime(29927): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
E/AndroidRuntime(29927): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
E/AndroidRuntime(29927): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
E/AndroidRuntime(29927): 	at android.view.View.measure(View.java:27131)
E/AndroidRuntime(29927): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
E/AndroidRuntime(29927): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/AndroidRuntime(29927): 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1173)
E/AndroidRuntime(29927): 	at android.view.View.measure(View.java:27131)
E/AndroidRuntime(29927): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4187)
E/AndroidRuntime(29927): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2936)
E/AndroidRuntime(29927): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3204)
E/AndroidRuntime(29927): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
E/AndroidRuntime(29927): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9965)
E/AndroidRuntime(29927): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
E/AndroidRuntime(29927): 	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
E/AndroidRuntime(29927): 	at android.view.Choreographer.doFrame(Choreographer.java:744)
E/AndroidRuntime(29927): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
E/AndroidRuntime(29927): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(29927): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(29927): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(29927): 	at android.app.ActivityThread.main(ActivityThread.java:8506)
E/AndroidRuntime(29927): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29927): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(29927): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
I/Process (29927): Sending signal. PID: 29927 SIG: 9
Lost connection to device.
```

My `gradle-wrapper.properties` file
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
```

This plugin also fails to run on ios , see issue #3 #2

**Comment by pacifio** [comment]
Also this doesn't work with `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip`

**Comment by pacifio** [comment]
Even your own example project fails to work 😕

**Comment by rkbi** [comment]
> Even your own example project fails to work confused

Are you sure? We got countless feedback that it works out of the box.
